services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80      # Main port for custom domains
      - 8080:80    # Alternative port for localhost access
    volumes:
      - ./src:/usr/share/nginx/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: nhatansteel
    user: "1000:1000"  # Sử dụng UID:GID của user hiện tại (thay bằng UID:GID của bạn nếu khác)

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    volumes:
      - ./config/php/versions/php-${PHP_VERSION}.ini:/usr/local/etc/php/conf.d/zzz-upload.ini
    depends_on:
      - db

  php:
    image: php:${PHP_VERSION:-8.4}-fpm
    container_name: php_app
    build:
      context: ./config/php
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.4}
    volumes:
      - ./src:/usr/share/nginx/html
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./config/php/versions/php-${PHP_VERSION}.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
      # - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    user: "1000:1000"  # Set non-root user (UID:GID)

volumes:
  wordpress:
  db:
