version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./src:/usr/share/nginx/html
      # - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: nhatansteel

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: nhatansteel
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: exampleuser
      PMA_PASSWORD: examplepass
      PMA_ARBITRARY: 1
    depends_on:
      - db

volumes:
  wordpress:
  db:
