version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: nhatansteel
    user: "1000:1000"  # Sử dụng UID:GID của user hiện tại (thay bằng UID:GID của bạn nếu khác)

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: nhatansteel
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: exampleuser
      PMA_PASSWORD: examplepass
      PMA_ARBITRARY: 1
    depends_on:
      - db

  php:
    image: php:8.4-fpm
    container_name: php_app
    build:
      context: ./config/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/share/nginx/html
      # - ./config/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      # - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    user: "1000:1000"  # Set non-root user (UID:GID)

volumes:
  wordpress:
  db:
